### ISSUE TITLE
List ignores parameters

### ISSUE THREAD

**Issue by swordbeta** [kiwiirc/irc-framework#101]
Per [RFC 1459](https://tools.ietf.org/html/rfc1459#section-4.2.6), /list is supposed to support parameters. According to irc-framework's [docs](https://github.com/kiwiirc/irc-framework/blob/master/docs/clientapi.md#list-paramn) it should too, but the code ignores any given parameters as seen [here](https://github.com/kiwiirc/irc-framework/blob/1cc8892f6bf5414e677f0d37daa5984b77b58374/src/client.js#L556).

**Comment by prawnsalad** [comment]
Fixed in master

**Comment by astorije** [comment]
@prawnsalad, do you have a roadmap/ETA for next release? :)

**Comment by prawnsalad** [comment]
Most likely after this PR has completed https://github.com/kiwiirc/irc-framework/pull/98
