### ISSUE TITLE
Server password and SASL password use the same variable

### ISSUE THREAD

**Issue by PolarizedIons** [kiwiirc/irc-framework#103]
Client only supports one password argument (`password`), and it is used as the server password (it sends `PASS <password>`) and for SASL authentication if supported. 

This makes it impossible to connect to a server with a password, and to authenticate via SASL unless the two passwords are the same

**Comment by neolectron** [comment]
same issue here. changed to standard irc module sadly

**Comment by richrd** [comment]
I'd like to point out that SASL auth also uses the users nick for logging in, instead of the users accountname which is also different from server account name.

It's not ideal but but doing something like this in SASL auth would be nice (unless a new SASL username option is introduced)
```
accountname = this.connection.options.username ? this.connection.options.username : this.connection.options.nick
```
