### ISSUE TITLE
CTCP VERSION / CLIENTINFO not triggering `ctcp request` events

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/irc-framework#115]

**Comment by MaxLeiter** [comment]
https://github.com/kiwiirc/irc-framework/blob/dadf4855890ec168856db6d10ab48e1b9cd2cc4d/src/commands/handlers/messaging.js#L87-L112 relevant lines

**Comment by prawnsalad** [comment]
Quick note; the version command is now emitted if the version client option is empty, just need to cover the other commands without requiring extra work from the bot devs.
