### ISSUE TITLE
What does channel.join() do?

### ISSUE THREAD

**Issue by Jayflux** [kiwiirc/irc-framework#121]
I was looking at this example, https://github.com/kiwiirc/irc-framework/blob/master/examples/bot.js#L62-L67

if bot.join() joins the channel, what is the purpose of channel.join()?

Thanks
btw if there's a general place to ask questions about this framework like an irc channel or something better let me know.

Jason

**Comment by MaxLeiter** [comment]
#kiwiirc on freenode is probably the best channel for questions
`channel.join()` is the same thing as `client.join('channel')`; it's just for convenience sake

**Comment by chovy** [comment]
`bot.join()` doesn't join my channel
