### ISSUE TITLE
Account field in message event is undefined even when user is logged in

### ISSUE THREAD

**Issue by Jayflux** [kiwiirc/irc-framework#122]
I've been using this over the weekend, and i want to make a feature that only works for registered users on freenode. 
I was told to use the account field for this. However when testing on my own user account it's still `undefined`.

```
{ type: 'privmsg',
  nick: 'Jayflux_',
  ident: '~Jayflux',
  hostname: 'unaffiliated/jayflux',
  target: '#web-testing',
  group: undefined,
  message: '!',
  tags: {},
  time: undefined,
  account: undefined,
  reply: [Function] }
```

Is this a known bug? Or am i doing this wrong?

**Comment by prawnsalad** [comment]
The account property is only available on networks that support it. Unfortunately freenode doesn't yet support this.

Specifically, the network must support these options which many up to date smaller networks do, http://ircv3.net/irc/#account-tracking
