### ISSUE TITLE
Release irc-framework? 🙏

### ISSUE THREAD

**Issue by astorije** [kiwiirc/irc-framework#123]
Hey @prawnsalad! Would you mind drafting a release with what's on `master`?

At the time of writing this issue, this is the diff: https://github.com/kiwiirc/irc-framework/compare/v2.9.1...68e28a8

Thanks!

/Cc @MaxLeiter @xPaw

**Comment by prawnsalad** [comment]
@astorije I'll be typing up release notes when a release is made. Currently waiting on a few issues to be closed such as #115 #120
