### ISSUE TITLE
Allow Twitch Membership Capability To Be Disabled

### ISSUE THREAD

**Issue by TownCube** [kiwiirc/irc-framework#128]
Currently the twitch.tv/membership capability is enabled by default with no way (that I could find) to disable it.

This capability results in a large amount of traffic for joins/parts as users start/stop watching which most bots don't care about. Bots mostly care about watching for commands and this just adds unnecessarily noise to that process.

Thanks for your great work on this framework.

**Comment by prawnsalad** [comment]
A bit late, but a good point. I've now removed `twitch.tv/membership` from the default list as it can now be requested specifically via `client.requestCap('twitch.tv/membership')`.
