### ISSUE TITLE
Deriving client username from who reply breaks ZNC extended username

### ISSUE THREAD

**Issue by kode54** [kiwiirc/irc-framework#131]
As of this commit, 4786e01cfbb9bb0411329dd98b3e36897c6cddf0, and this subsequent commit, 68e28a8ac48bdbe132d16537a3a222273123d938, breaks specifying the ZNC network name and/or connection identifier in the username field.

The client, The Lounge, will specify the username as "username/networkname", and then any time a /who reply comes in for my nickname, it will replace that Network object's username field with "username", and subsequent reconnects to that ZNC session will switch over to the first network in the list, and rejoin all of the channels from the previous network on the wrong session.

**Comment by prawnsalad** [comment]
Your client should be fixed to use ZNC correctly. ZNC expects `zncuser/freenode:yourpassword` as the connection password for multi network usage.

I'll keep this issue open though as I can see a case where the reported username may not match your specified username in general usage, but this is just an aesthetic thing.

**Comment by kode54** [comment]
From the [ZNC FAQ](https://wiki.znc.in/FAQ):

> If you have decent IRC client, you can just use "username" (or "ident") field for username, optional client identifier and network (for example User@phone/freenode) and "server password" field for password.

**Comment by DarthGandalf** [comment]
Also note that ZNC username is not the same as ident which ZNC itself sends to IRC server.
By default they are the same, but if they are different, reconnect would result in an invalid password, because username is wrong.

**Comment by DarthGandalf** [comment]
Btw, isn't this broken even without ZNC? If server prepends `~` to ident when it didn't get response from identd, in the best case 5 reconnects will result in `~~~~~foo`, if server even accepts `~` in username from client at all.

**Comment by xPaw** [comment]
Yeah I don't see why it's a good reason to update `username` based on server response. It should continue connecting with username that was initially passed into the framework.
