### ISSUE TITLE
Add support for webirc options

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#135]
I see they are already sent in `webircgateway`, so shouldn't be a problem to add here.

**Comment by prawnsalad** [comment]
I'll add it to the docs but this is already supported. In the client options:
~~~~~
webirc: {
	password: 'webirc password',
	username: 'typically just *. will be used moreso in webirc extensions currently being proposed',
	hostname: 'user.host.isp.net',
	ip: 'user.ip.goes.here',
},
~~~~~

https://github.com/kiwiirc/irc-framework/blob/master/src/client.js#L241

**Comment by xPaw** [comment]
I was talking about `options` which is the 5th parameter after `address` to specify things like `secure`.

**Comment by prawnsalad** [comment]
Ahh sorry, gotcha. I need to finalise those new extensions and get them into a draft to standardise the naming scheme before putting them into this lib. It's in webircgateway already as a few people are using that for ircv3 testing at the moment.

**Comment by TheMythPT** [comment]
Any news about this? It's very important for people that uses this lib, because without the `options` parameter, people will be locked out of `SSL only` channels.
I, personally, have had that issue already.

Best regards.

**Comment by prawnsalad** [comment]
@TheMythPT this is just waiting on the IRCv3 spec to be finalised as the names may change yet. Hopefully that gets done this week and then I can put it into webircgateway.

If your IRC server relies on unfinished IRC specs then you should downgrade to their stable versions.

**Comment by TheMythPT** [comment]
>this is just waiting on the IRCv3 spec to be finalised as the names may change yet. Hopefully that gets done this week and then I can put it into irc-framework.

Honestly, I didn't knew that the spec wasn't finished yet.

>If your IRC server relies on unfinished IRC specs then you should downgrade to their stable versions.

I'm using UnrealIRCd latest stable release. It was, probably, the very first to implement the option.

Then, let's hope that the spec is finalised soon. Thanks for the hard work. 😀

**Comment by TheMythPT** [comment]
So, any news? Been 6 months already and I'm still wondering if this is is already implemented and forgotten to close

**Comment by TheMythPT** [comment]
Hello. I don't like to be a "pain in the ass" but I'd expect that the spec for this was already finished.
When using TheLounge my users simply can't join SSL only channels due to the `:secure` tag not being sent.
I believe that this option should be added to the irc-framework, even if it's not finished/polished because everyone that wants to run a SSL only network needs it.

Thank you.

**Comment by finalhit** [comment]
Please add support for "secure" tag UnrealIRCd requires for WEBIRC gateways using SSL/TLS.

See:
https://forums.unrealircd.org/viewtopic.php?f=1&t=8775

> This is the regular WEBIRC format:
WEBIRC password gateway hostname ip
This indicates a secure client connection (NEW):
WEBIRC password gateway hostname ip :secure"


Meaning for secure connections in client.js:
```this.raw('WEBIRC', webirc.password, webirc.username, webirc.hostname, webirc.address);```
should become:
```this.raw('WEBIRC', webirc.password, webirc.username, webirc.hostname, webirc.address, "secure");```

**Comment by adamus1red** [comment]
Is it possible to get an update on this issue.
