### ISSUE TITLE
handle banned nicks IRC432

### ISSUE THREAD

**Issue by ItsOnlyBinary** [kiwiirc/irc-framework#136]
432 | ERR_ERRONEUSNICKNAME | RFC1459 | <nick> :<reason> | Returned after receiving a NICK message which contains a nickname which is considered invalid, such as it's reserved ('anonymous') or contains characters considered invalid for nicknames. This numeric is misspelt, but remains with this name for historical reasons :)

**Comment by prawnsalad** [comment]
This is already handled here https://github.com/kiwiirc/irc-framework/blob/c44bedef9a96cb7068c4910179e401e9add27360/src/commands/handlers/user.js#L118
