### ISSUE TITLE
Implement exponential backoff for reconnection attempts

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#140]
Right now reconnection runs on a set internal which is not ideal. Companies like Google suggest using exponentially increasing timers: https://developers.google.com/drive/v3/web/handle-errors#exponential-backoff.

https://en.wikipedia.org/wiki/Exponential_backoff

It's relatively simple to do: https://gist.github.com/kitcambridge/11101250#file-exponential-backoff-js-L2

**Comment by Frotty** [comment]
Will this ever happen? 😢

**Comment by xPaw** [comment]
If you want to work on it, then you can make it happen.
