### ISSUE TITLE
Expose extra data from WHOWAS

### ISSUE THREAD

**Issue by Zarthus** [kiwiirc/irc-framework#156]
https://github.com/kiwiirc/irc-framework/blob/622c3d7df5526aa4be487e4f6bcdf6d7ef94a5d1/src/commands/handlers/user.js#L283-L290

WHOWAS contains much more useful information: Account name, WHOISACTUALLY, and the date they were seen for instance. We should change it to be on ENDOFWHOWAS

the extra fields (assume they are nullable) are "server", "server_info"?, "account", "actualip", "actualhost", and maybe "date".)

**Comment by prawnsalad** [comment]
Could you open a PR with the changes you made?

**Comment by Zarthus** [comment]
I can, but I'd like to test them first before randomly guessing if my impl is correct (together with @Jay2k1 )
