### ISSUE TITLE
Question: Will this framework support multiple IRC server connections?

### ISSUE THREAD

**Issue by kamikazechaser** [kiwiirc/irc-framework#167]
I believe kiwiirc uses an in-built bouncer to facilitate multiple connections. Are there any plans to bring such a feature to this framework? At the moment there is no maintained independent bouncer implementation in Node.js.

**Comment by prawnsalad** [comment]
You can use as many connections as you like in this framework.

~~~javascript
let connection1 = new IRC.Client();
connection1.connect({host: 'irc.freenode.net', nick: 'bot1'});

let connection2 = new IRC.Client();
connection2.connect({host: 'irc.freenode.net', nick: 'bot2'});
~~~

This is the same way kiwiirc handles it internally.
