### ISSUE TITLE
Failed to construct 'WebSocket': The port 6667 is not allowed

### ISSUE THREAD

**Issue by DavidVerdier** [kiwiirc/irc-framework#193]
Hi, 

I want to use irc-framework in an application. I have a chrome error and websocket do you know why and how to fix this please?

![capture du 2019-02-24 12-42-30](https://user-images.githubusercontent.com/15361985/53300553-28376d80-3849-11e9-8d4a-9264b63f937d.png)

```js
import { Injectable } from '@angular/core';
import Irc from 'irc-framework/browser';

@Injectable({ providedIn: 'root' })
export class IrcService {
    private ircClient;
    private clientOpts = {};

    constructor() {
        this.clientOpts = {
            host: 'irc.europnet.org',
            port: 6667,
            nick: 'test'
        };

        this.ircClient = new Irc.Client();
    }

    connection(values) {
        console.log(values);
        this.ircClient.connect(this.clientOpts);
    }
}
```

**Comment by ItsOnlyBinary** [comment]
Chrome/Firefox etc block port 6667 (and others), you will need to use a different port for your websockets

**Comment by prawnsalad** [comment]
As the error says, you can't use port 6667 in a browser as browsers block certain ports to prevent abuse. It is also using a websocket while rc.europnet.org:6667 is not websocket capable.
