### ISSUE TITLE
Pull runes dependency from npm

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#207]
#204 changed the runes dependency to pull via git, and this breaks installing the package if the client has no git installed (think lightweight docker containers). Not to mention this dependency is not set to a specific version or hash, so it will put any latest code that exists in the git repo.

Can this dependency be published as an npm package, or the build process be fixed so it can built the upstream package properly?

**Comment by xPaw** [comment]
@prawnsalad or @vith can you fix this please?

**Comment by prawnsalad** [comment]
We're looking at removing the dependancy entirely as it's not updated or responsive to changes for some years now.

**Comment by vith** [comment]
Done in #208
