### ISSUE TITLE
How can I specify minimum TLS version and cipher suite?

### ISSUE THREAD

**Issue by pwhack** [kiwiirc/irc-framework#217]
Hi,

I'm looking to configure IRC server connections so they only use TLS v1.2 or higher as well as cipher suites that support Perfect Forward Secrecy. I _think_ the connection code for TLS is in https://github.com/kiwiirc/irc-framework/blob/master/src/transports/net.js#L104. Is there any way to pass in a configuration object to specify minimum version and ciphers? Or is it perhaps elsewhere? Node code isn't my strength, sorry.

Thanks!

**Comment by prawnsalad** [comment]
There is the `options` var in that function. These are the options passed into the `new irc.Client({..options..})` instance.
You've found the correct place for the tls connection and its config, and it does look like there are cipher suites available https://nodejs.org/api/tls.html#tls_tls_createsecurecontext_options

**Comment by pwhack** [comment]
Perfect, thank you!
