### ISSUE TITLE
multiline responses to `CAP LS 302` not handled correctly?

### ISSUE THREAD

**Issue by slingamn** [kiwiirc/irc-framework#218]
Here's what I know so far:

1. Both The Lounge (https://github.com/thelounge/thelounge/issues/3500) and Kiwi (https://github.com/kiwiirc/kiwiirc/issues/1193) have issues with multiline responses to `CAP LS 302`
1. irc-framework has code support for this, but it may not function correctly: https://github.com/kiwiirc/irc-framework/blob/3c8592992b5bf06be9d2b4481f9c39c9143e2fd3/src/commands/handlers/registration.js#L157
1. @xPaw thinks this is a bug in irc-framework, which sounds reasonable to me, but I don't have an isolated test case against irc-framework for it :-)

**Comment by xPaw** [comment]
The bug is here:
https://github.com/kiwiirc/irc-framework/blob/3c8592992b5bf06be9d2b4481f9c39c9143e2fd3/src/commands/handlers/registration.js#L151-L152

It resets `request_caps` which were calculated for the first LS line.
