### ISSUE TITLE
Should core-js be in dev dependencies?

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#224]
It's needed for the browser build as it's used by babel, does it need to be in production dependencies?

Same question for `regenerator-runtime`, as I don't see it being used directly.

**Comment by xPaw** [comment]
cc @vith for insight, as you added both of these.

**Comment by vith** [comment]
They're both used at runtime. Their usage is injected by babel, you can only see it when looking at the build output. They provide various polyfills to enable older browser support.

**Comment by xPaw** [comment]
Makes sense, thanks.
