### ISSUE TITLE
channel list is not triggered

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#24]
This should be checking `cache.channels.length` here: https://github.com/kiwiirc/irc-framework/blob/011b6e0f1c979d8d190b0b94ff87f4528da62a8e/src/commands/handlers/misc.js#L24

Also in `RPL_LISTEND` before sending `channel list end` it should send the remaining channels if `cache.channels` is not empty.

**Comment by prawnsalad** [comment]
Now fixed in master
