### ISSUE TITLE
Login to irc account

### ISSUE THREAD

**Issue by d3jr00** [kiwiirc/irc-framework#245]
Hi, how login with username and password to irc channel? simply add "password: 'ghffd'" not working

**Comment by prawnsalad** [comment]
It depends on the network. Most modern networks will use SASL so you would set the nick and password options. If the network doesn't support SASL then you may have to listen for the `registered` event and send the login command via `.say('nickserv', 'identify ' + password)`

**Comment by d3jr00** [comment]
Like this?:

var password = 'simplepassword'

bot.on('registered', function() {
	bot.say('nickserv', 'identify ' + password)
    console.log('Connected!');
    bot.join('#test000');
});

**Comment by prawnsalad** [comment]
Test it and see what happens. Does it work?

**Comment by d3jr00** [comment]
Nope. I try pn this chat: https://poorchat.net/channels/test

Public but if you wsnt write you must login. I dont know how

**Comment by prawnsalad** [comment]
Works for networks that use SASL:
~~~javascript
var bot = new IRC.Client();
bot.connect({
    host: 'irc.irc.com',
    tls: true,
    port: 6697,
    nick: 'somenick',
    password: 'somepassword',
});
~~~


Works for networks that don't use SASL but uses nickserv:
~~~javascript
var password = 'mypassword';
var username = 'myusername';

bot.on('registered', function() {
        bot.say('nickserv', 'identify ' + username + ' ' + password)
        console.log('Connected!');
        bot.join('#prawnsalad');
});
~~~

**Comment by d3jr00** [comment]
This example does not work for my chat. In python this code work:

irc = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
irc.connect((server,port))
irc.setblocking(False)
time.sleep(1)
irc.send(("USER "+botnick+" "+botnick+" "+botnick+" :Hi, I'm just a bot!\r\n").encode())
time.sleep(1)
irc.send(("NICK "+botnick+"\n").encode())
time.sleep(1)
irc.send(("LOGIN "+botnick+" "+password+"\n").encode())
time.sleep(3)
irc.send(("JOIN "+channel+"\n").encode())

and... I dont know how rewrite this in javascript

**Comment by prawnsalad** [comment]
`LOGIN` is not a standard command, that's why it doesn't work.

~~~javascript
var password = 'mypassword';
var username = 'myusername';

bot.on('registered', function() {
        bot.say('LOGIN', username + ' ' + password);
        console.log('Connected!');
        bot.join('#prawnsalad');
});
~~~

**Comment by d3jr00** [comment]
Still not. Can you try login on this chat and write as bot? I can give you login/pass
