### ISSUE TITLE
Is it possible to use in the browser with ports blocked?

### ISSUE THREAD

**Issue by mmahandev** [kiwiirc/irc-framework#265]
In Chrome for example I get the error `Uncaught DOMException: Failed to construct 'WebSocket': The port 6697 is not allowed.`

Virtually all IRC servers are on the 6XXX ports. Does this mean it's not possible to use within the browser?

**Comment by ItsOnlyBinary** [comment]
You need to connect to a websocket, not a tcp socket. if you run your own ircd then both [inspircd](https://docs.inspircd.org/3/modules/websocket/) & [unrealircd](https://www.unrealircd.org/docs/WebSocket_support) support websockets. The other option is a websocket <-> tcp proxy like [webircgateway](https://github.com/kiwiirc/webircgateway).

**Comment by mmahandev** [comment]
Thanks for replying so fast. It looks like a strictly only browser-based solution without running a server is not possible then. Unfortunate.
