### ISSUE TITLE
Publish NPM releases from a github action

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/irc-framework#283]
Since I'm handing the kiwi org lead to @ItsOnlyBinary I also need to add them as a maintainer to the NPM packages. I'll leave this up to the contributors if it's needed but it might be good to move the NPM publishing to a github action to speed up new releases.

https://github.com/marketplace/actions/npm-publish

**Comment by xPaw** [comment]
It's pretty simple, really: https://github.com/thelounge/thelounge-theme-solarized/blob/master/.github/workflows/release.yml

The only thing needed is to add the npm auth token in secrets.

**Comment by xPaw** [comment]
Fixed by #286
