### ISSUE TITLE
Auto-reconnection fails to re-register due to CAP negotiation

### ISSUE THREAD

**Issue by maxpoulin64** [kiwiirc/irc-framework#34]
Using the `auto_reconnect` option doesn't work because when the framework reconnects, it sends a `CAP LS` but doesn't do anything with the reply and ultimately never sends the `CAP END` that's needed for the server to continue.

```
CAP LS
NICK lounge-pr-test
USER lounge-user 0 * :The Lounge User
:test NOTICE Auth :*** Looking up your hostname...
:test NOTICE Auth :*** Looking up your ident...
:test CAP 630AAAAZB LS :away-notify extended-join account-notify sasl tls userhost-in-names
:test NOTICE Auth :*** Could not resolve your hostname: Domain name not found; using your IP address (127.0.0.1) instead.
ERROR :Closing link: (lounge-user@127.0.0.1) [Registration timeout]
```

**Comment by xPaw** [comment]
Slightly unrelated problem: `this.network.cap.negotiating` is never set to true.

In Kiwi it was set to true in `IrcConnection` creation. I suggest setting it to true just before sending `CAP LS`.

**Comment by maxpoulin64** [comment]
The original issue of this ticket is fixed (or at least for my point of view), so I will close this.
