### ISSUE TITLE
'invited' event not triggering?

### ISSUE THREAD

**Issue by Underdoge** [kiwiirc/irc-framework#340]
Hello,

I have the following code to log when someone invites the bot but for some reason it's not triggering:

```
bot.on('invited', function(event){
    console.log("User " + event.nick + " invited us to " + event.channel);
});
```

Other events like 'connected', 'message', etc. trigger just fine and I can act on them in the same way I described in the code snippet, but for some reason 'invited' is simply not triggering.

Am I doing something wrong?

Thank you

**Comment by ItsOnlyBinary** [comment]
I think you are looking for 'invite' event, 'invited' is for when your bot has invited another user
