### ISSUE TITLE
Problem RPL_WHOISCOUNTRY on UnrealIRCd 6.0.x : Does not retrieve country code

### ISSUE THREAD

**Issue by Madriix** [kiwiirc/irc-framework#341]
Today I updated irc-framework in my project, it hadn't been updated for 1 year. I encountered a bug on this file:
https://github.com/kiwiirc/irc-framework/pull/318/commits/34683a7181aa1d3c384a2cf914149f13019906b8
https://github.com/kiwiirc/irc-framework/blob/master/src/commands/handlers/user.js#L294

I had to replace this line:
`cache.country = command.params[command.params.length - 1];`
by this one:
`cache.country = command.params[2];`

The first line displays this entire line: is connecting from France
and the second line replaced, it displays only country codes like FR, BE, DE ...

**Comment by ItsOnlyBinary** [comment]
Could you please console.log(command) for a whois, this has been reported before, but is different for both inspircd and unrealircd. I would need to find a way that works for both.

**Comment by ItsOnlyBinary** [comment]
Thanks, so you are just wanting the country code? not the actual string with name?

**Comment by Madriix** [comment]
Yes just "CA"
