### ISSUE TITLE
Can't join "hidden from list" channels

### ISSUE THREAD

**Issue by Nemoopla** [kiwiirc/irc-framework#357]
It's hidden channel (not on the server list) with no password. I can join it with any irc client with #channelname, but can't connect with code. I can join any other channel on this server through code. What could be the problem?

**Comment by Nemoopla** [comment]
So i figured out that i can't connect to any hidden channels
how can i do it? 
![image](https://user-images.githubusercontent.com/128919928/227735375-d644fbe1-20d8-4587-acef-5380e0cde587.png)

**Comment by brunnre8** [comment]
don't see the code doing anything but emit a raw join event.
If I were you, use the raw event and log everything that happens, then go from there.

```js
irc.on("raw", function (message) {
// whatever
})
```

**Comment by Nemoopla** [comment]
Thank you for response. I realised that its SSL only channel. So i need to cofigure `webirc` parameter but i can't figure out how to do it right. I keep getting `ERROR :Closing link [WEBIRC: you don't match any configured WebIRC hosts.]`

```
webirc: {
        password: '',
        username: '*',
        hostname: 'users.host.isp.net',
        ip: '1.1.1.1',
        options: {
            secure: true,
            'local-port': 6697,
            'remote-port': 21726,
        },
```

How to cinfigure it right? Do i need to put certificates or it's unnecessary?

**Comment by Nemoopla** [comment]
solved with `tls: true`
