### ISSUE TITLE
how do I ignore a list of nicks?

### ISSUE THREAD

**Issue by ralyodio** [kiwiirc/irc-framework#365]
I want to ignore output from other bots given a list of bot nicks.

How can I do this?

**Comment by ItsOnlyBinary** [comment]
This is something you would need to write yourself in your handlers or as a middleware.

I suggest using an object to store the nicks as keys in lowercase to prevent duplicates and make for quick checking and removal.

**Comment by ItsOnlyBinary** [comment]
https://github.com/kiwiirc/irc-framework/blob/master/examples/bot.js#L28
