### ISSUE TITLE
TLS Connect

### ISSUE THREAD

**Issue by SheiylaDev** [kiwiirc/irc-framework#378]
Hi, I would like to know how to connect the bot on the tls port of my unrealircd server?

* Don't tell me how to change the port on the bot but how to add what is needed to connect in tls with my bot.

Thanks

**Comment by ItsOnlyBinary** [comment]
This really could do with being in the documentation somewhere :(

```
bot.connect({
	host: 'irc.freenode.net',
	port: 6697,
	tls: true,
	nick: 'prawnsbot'
});
```

**Comment by SheiylaDev** [comment]
I have tested but the bot does not connect and I have no message.

**Comment by SheiylaDev** [comment]
can you give me an example of a bot to see if I did well on my side?

**Comment by ItsOnlyBinary** [comment]
https://gist.github.com/ItsOnlyBinary/a171695cd33685eedfaab64a00bcc3cb

maybe also want to listen for 'close' or 'socket close' events or maybe 'error' events

https://github.com/kiwiirc/irc-framework/blob/master/docs/events.md

**Comment by SheiylaDev** [comment]
I tested with an empty project and your bot and in normal it launched but not in tls.

**Comment by brunnre8** [comment]
can you like hop into the #kiwiirc on libera.chat ?
The issue tracker isn't really the right format for this conversation.

Would cut down the roundtrip times considerably

**Comment by SheiylaDev** [comment]
1715721266015 [S] ERROR :NON-TLS command received on TLS-only port. Check your connection settings.

**Comment by SheiylaDev** [comment]
rejectUnauthorized: false,
tls: true,

Done :)
