### ISSUE TITLE
Leave ctcp handling to the consumer

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#39]
Basically just remove this: https://github.com/kiwiirc/irc-framework/blob/f501a8786ececd4d14a898337b4d7cf7e79c4d2d/src/commands/handlers/messaging.js#L79-L98

**Comment by ItsOnlyBinary** [comment]
This behaviour can be obtained by setting version within options object falsy

eg
```
bot.connect({
    host: 'irc.libera.chat',
    port: 6697,
    tls: true,
    nick: 'testbot',
    version: '',
});
```
