### ISSUE TITLE
Always prepend a colon when sending privmsg

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#53]
One of @thelounge users ran into issue where messages without spaces (no colon prepended) are being ignored by the server.

**Comment by dgw** [comment]
Probably fixed by #45, whenever that gets merged in.

**Comment by xPaw** [comment]
@dgw It won't. There won't be any colons added to a `hello` message.

**Comment by prawnsalad** [comment]
Closing due to fix applied some releases ago

**Comment by xPaw** [comment]
@prawnsalad was it though?

**Comment by prawnsalad** [comment]
Ah sorry, re-read this specific issue. So the issue is the server doesn't parse IRC messages correctly. Which IRCd was it?

**Comment by xPaw** [comment]
I believe it was some custom proxy.

**Comment by prawnsalad** [comment]
Then they should fix the proxy.
