### ISSUE TITLE
Support extending a client via .use()

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/irc-framework#6]
Not thought about it technically but the ability to extend the IRC bot via the common `.use()` function. Would be useful for adding extra extensions or services that are not part of the core.

Something similar to:
~~~javascript
var SomeIrcExtension = require('someircextension');
var IRC = require('irc-framework');

var bot = new IRC.Bot('irc.freenode.net', 6667, 'prawnsbot');
bot.use(SomeIrcExtension());

bot.connect();
~~~

**Comment by M2Ys4U** [comment]
Hmm, what would the extension API look like here?

We could pass in every message received, so something like 
```javascript
function (client, message, next) {
    if (message.command === 'PRIVMSG') {
        message.params[message.params.length - 1].replace('the cloud', 'my butt');
    }
    next(message);
}
```
which would do what [cloud to butt](https://github.com/panicsteve/cloud-to-butt) does on the web, but on IRC.

If `next` is not called then processing for the command is finished, if it's called without an argument then we pass the original message to the next handler in the queue, and if it's called with an argument then we pass that argument as  `message` to the next handler.

Alternatively, we could allow people using the API to only hook in to specific commands, by passing that command in as the first argument to `use`, like: 
```javascript
use('privmsg', myFunction);
```
that way less code gets called for each message, and a missing `next()` won't bring down the entire client.

Thinking about it, we could also use this API internally to structure our handlers - it'd force us to use a bit more discipline and make sure that we provide other consumers of the lib the things they need.

Thoughts?
