### ISSUE TITLE
whois is not case insensitive

### ISSUE THREAD

**Issue by PolarizedIonss** [kiwiirc/irc-framework#63]
(this is in the context of [the lounge](https://github.com/thelounge/lounge), but was told to report here)

When making a whois, the server responds with the correct capitalization, but the client seems to not match case-insensitively.

For example, '/whois polarizedions', won't match if his name is PolarizedIons

whois in The Lounge: http://i.imgur.com/Xi7KMGu.png
whois in netcat: http://i.imgur.com/fL6p1za.png

**Comment by kode54** [comment]
Further adding that it doesn't seem to affect [the lounge](http://github.com/thelounge/lounge/)'s matching of buffer names, as repeating the /whois with the correct capitalization still goes to the all-lower-case named buffer, hinting that this case sensitivity is within irc-framework. Wherever it happens to store up a list of outgoing queries that it expects a reply for.

Upon further inspection, the issue appears to be with [src/commands/handlers/user.js#L51](https://github.com/kiwiirc/irc-framework/blob/867b5670e2f73fe2095e10d61522e91726de394c/src/commands/handlers/user.js#L51) and [src/commands/handler.js#L158](https://github.com/kiwiirc/irc-framework/blob/7b616172ecb91be7ce7baa01887374ad8374a9a6/src/commands/handler.js#L158), specifically, it appears to be using an array's keys as a hash table, which is case sensitive. It needs to use some sort of key system that's case insensitive, or it needs to apply a tolower or similar filter to the key before referencing or storing values.

**Comment by kode54** [comment]
Fixed by #80
