### ISSUE TITLE
`registered` event is triggered before registration properties set

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/irc-framework#67]
https://github.com/kiwiirc/irc-framework/blob/master/src/client.js#L169
1. This event should be triggered _after_ the internal properties have been updated.
2. Due to the `registered` and `connected` events being triggered in different places, they are both triggered at different times from the client instance.

**Comment by astorije** [comment]
Is this fixed by the commit above? Has it made it into a release yet? Thanks @prawnsalad!

**Comment by prawnsalad** [comment]
@astorije I need to update some docs, but this will be in a release this weekend

**Comment by astorije** [comment]
Thanks @prawnsalad!
