### ISSUE TITLE
Document version bumps

### ISSUE THREAD

**Issue by astorije** [kiwiirc/irc-framework#71]
At the moment, it is rather difficult to compare versions, required in other projects using this one as a dependency when upgrading it.
So far, the only (non-optimal) ways I've found is to:

- Find commits updating the version number in `package.json`, copying the commit hashes and using GitHub's `/compare/` URL. For example, this is the diff between 2.5.0 and 2.5.1: https://github.com/kiwiirc/irc-framework/compare/948a4b285f61d95dcb413f0a783f5c514f2672ae...90a69d300fa215d7c64f370e6f5168c5314164d7
- Using https://david-dm.org/, which manages to find corresponding commit hashes to a version

It would be great if you could have a `CHANGELOG.md` file and/or use git tags and/or use GitHub releases. While first and last options require manual redaction of their content (probably the same though, so it can be one or the other), you can use second one as a 1:1 connection between what's in git tags and what in npm releases, which makes it way easier to follow new releases, compare versions, etc.

At the simplest, you can use `npm version [major|minor|patch]` on your laptop instead of updating the `package.json` yourself. This commits a `package.json` bump just like you do, and creates a git tag. Then push with `git push --follow-tags` and both commit and tag will be pushed.

I see you have tests for this project, so if you end up setting up Travis CI to run them, you can also set it up to release to npm release for you. [See how we are doing for The Lounge](https://github.com/thelounge/lounge/blob/778db968b3f6f1700bc591bc9e9293bf17fba7f9/.travis.yml#L18-L27).

Hope that helps!

**Comment by prawnsalad** [comment]
I do plan to start using release tags soon so you can compare things easier. The tests though.. they obviously need a lot of work :) I'll take a look at the travis setup to get that automated as it's about time I jumped into that.

Didn't know about the automated `npm version` helper though, thanks for that tip!
