### ISSUE TITLE
Deprecated Packages

### ISSUE THREAD

**Issue by ellisgl** [kiwiirc/irc-framework#84]
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

**Comment by MaxLeiter** [comment]
Worth noting that none of these dependencies are directly used by irc-fw (at least, afaik). They're used by dependencies

https://github.com/kiwiirc/irc-framework/blob/master/package.json

**Comment by ellisgl** [comment]
Ah - need to investigate which packages are using those and bug them =P
