### ISSUE TITLE
Should the localAddress lookup be part of the lib or be left to the application?

### ISSUE THREAD

**Issue by prawnsalad** [kiwiirc/irc-framework#9]
In connection.js. All other libs leave this to the application. If it errors out then the application can handle it.

**Comment by M2Ys4U** [comment]
I suppose we could put in the ability to pass in a DNS resolution function to the connection constructor - if none is passed in we use our own.

**Comment by prawnsalad** [comment]
No longer looking up the address family - leaving it down to the OS or application.
