### ISSUE TITLE
connect does not reset requested_disconnect

### ISSUE THREAD

**Issue by xPaw** [kiwiirc/irc-framework#91]
It's only set to false in the constructor, which makes it impossible to disconnect and connect back to the network.

**Comment by dgw** [comment]
Related to thelounge/lounge#917 or a different issue?

**Comment by xPaw** [comment]
Sounds like it.

**Comment by prawnsalad** [comment]
@xPaw Try putting a `that.requested_disconnect = false;` after this line and see how it does. https://github.com/kiwiirc/irc-framework/blob/master/src/connection.js#L93

**Comment by xPaw** [comment]
I'm on mobile for the next week, but that's how I expected to fix it. Or in the connect() method.
